pipeline {
    agent {
        docker {
            image 'all4dich/search-request-consumer:latest'
            label 'master'
            //args '--network host'
        }
    }
    stages {
        stage('Get methods') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nota', passwordVariable: 'JENKINS_PASSWORD', usernameVariable: 'JENKINS_USERNAME')]) {
                    sh 'python3 /work/src/rabbitmq/consumer.py  --jenkins_url $JENKINS_URL --jenkins_username $JENKINS_USERNAME --jenkins_password $JENKINS_PASSWORD --target_job_name $TARGET_JOB_NAME --queue_name $QUEUE_NAME --message_server_host $MESSAGE_SERVER_HOST'
                }
            }
        }
    }
}

